added bin/bash

diff --git a/env0.plugin.yaml b/env0.plugin.yaml
--- a/env0.plugin.yaml
+++ b/env0.plugin.yaml
@@ -7,6 +7,7 @@ inputs:
 
 run:
   exec: |
+    #!/bin/bash
     bucketName=$(cat $ENV0_TF_PLAN_JSON | jq -r ".variables.bucket_name.value")
-    echo "$bucketName"
-    [ "${bucketName}" = "env0"* ] || { echo "bucket name does not start with env0"; exit 1; }
+    echo $bucketName
+    if [[ ! $bucketName == "env0"* ]]; then echo "error" && exit 1; fi
